export default [
	'Thịt kho',
	'Thịt rán',
	'Gà nấu vang và cỏ xạ hương',
	'唐揚げ',
	'Gà rán',
	'Gà xào sả ớt',
	'Phở gà',
	'Cá hồi nấu kem',
	'Gà chiên nước mắm',
	'Bò xào',
	'Bò kho',
	'Bún bò Huế',
	'Canh sườn',
	'Sườn xào',
	'Bún sườn',
	'Khoai tây nhồi',
	'Mỳ ý',
	'Nui xào',
	'Súp gà',
	'Tôm chiên',
	'Tôm rang thịt',
	'Gà nấm xào kem',
	'Ba chỉ cuộn nấm',
	'Bít tết',
	'Cá kho',
	'Cá nướng',
	'Xôi xéo',
	'Cà ri gà',
	'Cơm rang',
	'Nem',
	'Bánh mỳ',
	'Cơm trộn',
	'Bò viên sốt hương',
	'Thịt lợn xào cà tím',
	'Mực xào',
	'Canh khoai sọ',
	'Bò viên sả chiên',
	'Cháo gà',
	'Tôm xào bí ngòi',
	'Cá cơm khô rang hạt óc chó',
	'Bạch tuộc xào sa tế + ớt + hành tây',
	'Bò xào đỗ xanh',
	'Canh hến cải chíp'
];
